version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Install phase..."
      - java -version
      - mvn -version

  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn -version
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-kubernet.jar
  discard-paths: yes